cc_binary(
    name = "expr",
    srcs = [
        "expr.c",
        "testtools.c",
        "testtools.h",
        "//:tools",
    ],
    copts = [
        "--undefine-macro DEBUG",
        "-Wall",
        "-Wextra",
        "-Wconversion",
    ],
)

cc_binary(
    name = "kadai",
    srcs = [
        "kadai.c",
        "testtools.c",
        "testtools.h",
        "//:tools",
    ],
    copts = [
        "--undefine-macro DEBUG",
        "-Wall",
        "-Wextra",
        "-Wconversion",
    ],
)

cc_binary(
    name = "quote",
    srcs = [
        "quote.c",
        "testtools.c",
        "testtools.h",
        "//:tools",
    ],
    copts = [
        "--undefine-macro DEBUG",
        "-Wall",
        "-Wextra",
        "-Wconversion",
    ],
)
